name: "Build Project"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-code-quality:
    name: "Verify Code Quality"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Check sortpom
        run: mvn -B sortpom:verify
      - name: Check Java Code Formatting
        run: mvn -B fmt:check
  run-code-tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Test Code
        run: mvn -B verify